In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_excel('/content/combined_issues.xlsx')

In [3]:
df.head()

id                                              title state  \
0  1932752667  [FullSimplify] Produces syntactically incorrec...  open   
1  1928532015  Cannot use word `_offset` in local variable na...  open   
2  1926687687  Add `assemblyJson` as an alias for `legacyAsse...  open   
3  1890794042  Boost-version-dependent trailing slash in rela...  open   
4  1890707839  Backslash intepretation in relative import pat...  open   

             created_at            updated_at closed_at  comments  \
0  2023-10-09T10:24:01Z  2023-10-13T13:43:56Z       NaN         1   
1  2023-10-05T15:12:51Z  2023-10-06T17:22:56Z       NaN         1   
2  2023-10-04T17:36:50Z  2023-10-04T17:36:50Z       NaN         0   
3  2023-09-11T15:44:49Z  2023-09-11T15:57:44Z       NaN         2   
4  2023-09-11T14:58:55Z  2023-09-11T15:29:26Z       NaN         4   

  assignee_names  assignee_count  \
0             []               0   
1             []               0   
2             []               0   
3             []               0   
4             []               0   

                                         label_names  label_count  \
0  ['bug :bug:', 'testing :hammer:', 'low effort'...            5   
1  ['bug :bug:', 'medium effort', 'low impact', '...            4   
2  ['protocol design :crystal_ball:', 'low effort...            5   
3  ['bug :bug:', 'low effort', 'low impact', 'mus...            4   
4  ['bug :bug:', 'low effort', 'low impact', 'mus...            4   

   pr_associated  comment_priority  \
0              0                 3   
1              0                 3   
2              0                 3   
3              0                 2   
4              0                 1   

                                          top_labels  Top_label_1  \
0  ['bug :bug:', 'external contribution :star:', ...            1   
1  ['bug :bug:', 'external contribution :star:', ...            1   
2  ['bug :bug:', 'external contribution :star:', ...            0   
3  ['bug :bug:', 'external contribution :star:', ...            1   
4  ['bug :bug:', 'external contribution :star:', ...            1   

   Top_label_2  Top_label_3  priority  
0            0            0         1  
1            0            0         1  
2            0            0         1  
3            0            0         1  
4            0            0         1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11537 entries, 0 to 11536
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   id                11537 non-null  int64 
 1   title             11537 non-null  object
 2   state             11537 non-null  object
 3   created_at        11537 non-null  object
 4   updated_at        11537 non-null  object
 5   closed_at         7747 non-null   object
 6   comments          11537 non-null  int64 
 7   assignee_names    11537 non-null  object
 8   assignee_count    11537 non-null  int64 
 9   label_names       11537 non-null  object
 10  label_count       11537 non-null  int64 
 11  pr_associated     11537 non-null  int64 
 12  comment_priority  11537 non-null  int64 
 13  top_labels        11537 non-null  object
 14  Top_label_1       11537 non-null  int64 
 15  Top_label_2       11537 non-null  int64 
 16  Top_label_3       11537 non-null  int64 
 17  priority    

In [5]:
df.describe()

id      comments  assignee_count   label_count  \
count  1.153700e+04  11537.000000    11537.000000  11537.000000   
mean   1.548334e+09      4.651036        0.298865      3.882205   
std    3.331343e+08      5.770016        0.479604      1.875986   
min    1.743948e+08      0.000000        0.000000      1.000000   
25%    1.382611e+09      2.000000        0.000000      3.000000   
50%    1.606678e+09      3.000000        0.000000      4.000000   
75%    1.821550e+09      6.000000        1.000000      5.000000   
max    1.976175e+09    150.000000        3.000000     28.000000   

       pr_associated  comment_priority   Top_label_1   Top_label_2  \
count   11537.000000      11537.000000  11537.000000  11537.000000   
mean        0.302158          1.735460      0.501604      0.263067   
std         0.459213          0.860232      0.500019      0.440317   
min         0.000000          1.000000      0.000000      0.000000   
25%         0.000000          1.000000      0.000000      0.000000   
50%         0.000000          1.000000      1.000000      0.000000   
75%         1.000000          3.000000      1.000000      1.000000   
max         1.000000          3.000000      1.000000      1.000000   

        Top_label_3      priority  
count  11537.000000  11537.000000  
mean       0.223455      2.377308  
std        0.416579      0.757337  
min        0.000000      1.000000  
25%        0.000000      2.000000  
50%        0.000000      3.000000  
75%        0.000000      3.000000  
max        1.000000      3.000000

In [6]:
print("Missing Values:")
print(df.isnull().sum())


Missing Values:
id                     0
title                  0
state                  0
created_at             0
updated_at             0
closed_at           3790
comments               0
assignee_names         0
assignee_count         0
label_names            0
label_count            0
pr_associated          0
comment_priority       0
top_labels             0
Top_label_1            0
Top_label_2            0
Top_label_3            0
priority               0
dtype: int64


In [7]:
columns_to_drop = ['id', 'updated_at', 'created_at','closed_at','title','top_labels', 'state', 'assignee_names', 'label_names']
df = df.drop(columns=columns_to_drop)
df

comments  assignee_count  label_count  pr_associated  comment_priority  \
0             1               0            5              0                 3   
1             1               0            4              0                 3   
2             0               0            5              0                 3   
3             2               0            4              0                 2   
4             4               0            4              0                 1   
...         ...             ...          ...            ...               ...   
11532         4               0            4              0                 1   
11533         3               1            2              0                 1   
11534         2               0            3              0                 2   
11535         0               0            3              0                 3   
11536         2               0            3              0                 2   

       Top_label_1  Top_label_2  Top_label_3  priority  
0                1            0            0         1  
1                1            0            0         1  
2                0            0            0         1  
3                1            0            0         1  
4                1            0            0         1  
...            ...          ...          ...       ...  
11532            0            1            0         2  
11533            0            0            0         3  
11534            0            0            0         3  
11535            0            0            0         3  
11536            0            0            0         3  

[11537 rows x 9 columns]

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [9]:
labeled_data = df[df['priority'].notnull()]
unlabeled_data = df[df['priority'].isnull()]


In [10]:
X = df.drop('priority', axis=1)
Y = labeled_data['priority']


In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=101)

In [12]:
model = RandomForestClassifier(n_estimators=100, random_state=101)
model.fit(X_train, Y_train)

RandomForestClassifier(random_state=101)

In [13]:
pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, pred)
classification_rep = classification_report(Y_test, pred)

print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", classification_rep)

Accuracy: 0.68
Classification Report:
               precision    recall  f1-score   support

           1       0.48      0.46      0.47       384
           2       0.58      0.58      0.58       660
           3       0.80      0.80      0.80      1264

    accuracy                           0.68      2308
   macro avg       0.62      0.62      0.62      2308
weighted avg       0.68      0.68      0.68      2308



In [14]:
unlabeled_data = pd.read_excel('/content/unlabelledData.xlsx')
unlabeled_data.shape

(5000, 18)

In [15]:
print("Missing Values:")
print(unlabeled_data.isnull().sum())


Missing Values:
id                     0
title                  0
state                  0
created_at             0
updated_at             0
closed_at           1030
comments               0
assignee_names         0
assignee_count         0
label_names            0
label_count            0
pr_associated          0
comment_priority       0
top_labels             0
Top_label_1            0
Top_label_2            0
Top_label_3            0
priority            5000
dtype: int64


In [16]:
columns_to_drop = ['id', 'updated_at', 'created_at','closed_at','title','top_labels', 'state', 'assignee_names', 'label_names']
unlabeled_data = unlabeled_data.drop(columns=columns_to_drop)
unlabeled_data

comments  assignee_count  label_count  pr_associated  comment_priority  \
0            1               0            1              1                 3   
1            0               0            2              1                 3   
2            1               0            2              1                 3   
3            2               0            1              0                 2   
4            0               0            1              0                 3   
...        ...             ...          ...            ...               ...   
4995         4               1            2              1                 1   
4996         1               0            2              1                 3   
4997         2               0            1              0                 2   
4998         2               0            1              0                 2   
4999         2               1            2              0                 2   

      Top_label_1  Top_label_2  Top_label_3  priority  
0               1            0            0       NaN  
1               1            0            1       NaN  
2               1            0            1       NaN  
3               0            1            0       NaN  
4               0            1            0       NaN  
...           ...          ...          ...       ...  
4995            1            0            1       NaN  
4996            1            0            1       NaN  
4997            0            1            0       NaN  
4998            0            0            0       NaN  
4999            0            1            0       NaN  

[5000 rows x 9 columns]

In [17]:
df = df.reset_index(drop=True)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix

In [20]:
num_iterations = 3

for iteration in range(num_iterations):
    #Pseudo-Labeling
    unlabeled_features = unlabeled_data.drop('priority', axis=1)
    pseudo_labels = model.predict(unlabeled_features)

    #new DataFrame for pseudo-labeled data
    pseudo_labeled_data = unlabeled_data.copy()
    pseudo_labeled_data['priority'] = pseudo_labels

    # Combine pseudo-labeled data with the labeled data for the next iteration
    combined_data = pd.concat([labeled_data, pseudo_labeled_data], ignore_index=True)


Iteration 1 - Model Accuracy: 0.7755048972869897
Iteration 2 - Model Accuracy: 0.7755048972869897
Iteration 3 - Model Accuracy: 0.7755048972869897


In [25]:
X_train_combined = combined_data.drop('priority', axis=1)
y_train_combined = combined_data['priority']

In [26]:
model = RandomForestClassifier(random_state=101)
model.fit(X_train_combined , y_train_combined)

RandomForestClassifier(random_state=101)

In [27]:
X_eval = df.drop('priority', axis=1)
y_eval = df['priority']

In [28]:
newpred = model.predict(X_eval)
accuracy = accuracy_score(y_eval, newpred)
print(f'Iteration {iteration + 1} - Model Accuracy: {accuracy}')


Iteration 3 - Model Accuracy: 0.7755048972869897


In [31]:
print(confusion_matrix(y_eval, newpred))
print('\n')
print(classification_report(y_eval, newpred))

[[1118  453  382]
 [ 343 2326  609]
 [ 222  581 5503]]


              precision    recall  f1-score   support

           1       0.66      0.57      0.61      1953
           2       0.69      0.71      0.70      3278
           3       0.85      0.87      0.86      6306

    accuracy                           0.78     11537
   macro avg       0.73      0.72      0.73     11537
weighted avg       0.77      0.78      0.77     11537



In [35]:
combined_data.tail()

comments  assignee_count  label_count  pr_associated  comment_priority  \
16532         4               1            2              1                 1   
16533         1               0            2              1                 3   
16534         2               0            1              0                 2   
16535         2               0            1              0                 2   
16536         2               1            2              0                 2   

       Top_label_1  Top_label_2  Top_label_3  priority  
16532            1            0            1         3  
16533            1            0            1         3  
16534            0            1            0         2  
16535            0            0            0         2  
16536            0            1            0         2

In [36]:
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16537 entries, 0 to 16536
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   comments          16537 non-null  int64
 1   assignee_count    16537 non-null  int64
 2   label_count       16537 non-null  int64
 3   pr_associated     16537 non-null  int64
 4   comment_priority  16537 non-null  int64
 5   Top_label_1       16537 non-null  int64
 6   Top_label_2       16537 non-null  int64
 7   Top_label_3       16537 non-null  int64
 8   priority          16537 non-null  int64
dtypes: int64(9)
memory usage: 1.1 MB
